server:
    port: '${PORT:8082}'
eureka:
    client:
        serviceUrl:
            defaultZone: '${EUREKA_URL:http://localhost:8761}/eureka/'
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
ribbon:
    eureka:
        enabled: true
spring:
    kafka:
        bootstrap-servers: 127.0.0.1:9092
        topics: helloworld.t,
            communicator.t,
            rubeus.t